#!/bin/bash
ufw allow ssh
ufw allow http
ufw logging off
ufw enable

apt-get update
apt-get install mysql-server php5-fpm php-pear php5-common php5-mysql php-apc php5-gd nginx

mkdir -p /var/www/
chown nginx:nginx /var/www/
chmod 775 /var/www

cp ./php.ini /etc/php5/fpm
cp ./www.conf /etc/php5/fpm/pool.d

service nginx restart
service php5-fpm restart
